Controllers/AbsencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gestionabscence.Models;
using GestionAbscences.ViewModel;

namespace GestionAbscences.Controllers
{
    public class AbsencesController : Controller
    {
        private readonly MyDbContext _context;

        public AbsencesController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Absences
        public async Task<IActionResult> Index()
        {
            var myDbContext = _context.Absences.Include(a => a.Student).Include(a => a.Student.User).Include(a => a.Subject);
            return View(await myDbContext.ToListAsync());
        }

        // GET: Absences/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var absences = await _context.Absences
                .Include(a => a.Student)
                .Include(a => a.Subject)
                .FirstOrDefaultAsync(m => m.AbsenceId == id);
            if (absences == null)
            {
                return NotFound();
            }

            return View(absences);
        }

        // GET: Absences/Create
        public IActionResult Create()
        {
            var users = _context.Users.ToList().Where(x => x.Role == "Student");
            var subjects = _context.Subjects.ToList();
            ViewData["StudentId"] = new SelectList(users, "Id", "FullName");
            ViewData["SubjectId"] = new SelectList(subjects, "SubjectId", "SubjectName");
            return View();
        }

        // POST: Absences/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Absences absences)
        {
         
                _context.Add(absences);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
           
        }

        // GET: Absences/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var absences = await _context.Absences.FindAsync(id);
            if (absences == null)
            {
                return NotFound();
            }
            var users = _context.Users.ToList().Where(x => x.Role == "Student");
            var subjects = _context.Subjects.ToList();
            ViewData["StudentId"] = new SelectList(users, "Id", "FullName");
            ViewData["SubjectId"] = new SelectList(subjects, "SubjectId", "SubjectName");
            return View(absences);
        }

        // POST: Absences/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AbsenceId,HoursNumber,Date,StudentId,SubjectId")] Absences absences)
        {
            if (id != absences.AbsenceId)
            {
                return NotFound();
            }

                try
                {
                    _context.Update(absences);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AbsencesExists(absences.AbsenceId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
        }

        // GET: Absences/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var absences = await _context.Absences
                .Include(a => a.Student)
                .FirstOrDefaultAsync(m => m.AbsenceId == id);
            if (absences == null)
            {
                return NotFound();
            }

            return View(absences);
        }

        // POST: Absences/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var absences = await _context.Absences.FindAsync(id);
            if (absences != null)
            {
                _context.Absences.Remove(absences);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AbsencesExists(int id)
        {
            return _context.Absences.Any(e => e.AbsenceId == id);
        }
    }
}

Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using gestionabscence.Models;

namespace GestionAbscences.Controllers
{
    public class GroupsController : Controller
    {
        private readonly MyDbContext _context;

        public GroupsController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            return View(await _context.Groups.ToListAsync());
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.GroupId == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("GroupId,GroupName")] Group group)
        {
            Console.WriteLine("ModelState.IsValid");
            Console.WriteLine(ModelState.IsValid);
            ModelState.Remove("Students");
            ModelState.Remove("GroupSubjects");


            foreach (var modelState in ModelState.Values)
            {
                foreach (var error in modelState.Errors)
                {
                    // Log or debug the error messages
                    var errorMessage = error.ErrorMessage;
                    var exception = error.Exception;
                    Console.WriteLine(errorMessage);
                    Console.WriteLine(exception);
                    // Handle the error appropriately
                }
            }
            if (ModelState.IsValid)
            {
                _context.Add(group);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(group);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups.FindAsync(id);
            if (@group == null)
            {
                return NotFound();
            }
            return View(@group);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("GroupId,GroupName")] Group @group)
        {
            if (id != @group.GroupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@group);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GroupExists(@group.GroupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@group);
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @group = await _context.Groups
                .FirstOrDefaultAsync(m => m.GroupId == id);
            if (@group == null)
            {
                return NotFound();
            }

            return View(@group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @group = await _context.Groups.FindAsync(id);
            if (@group != null)
            {
                _context.Groups.Remove(@group);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GroupExists(int id)
        {
            return _context.Groups.Any(e => e.GroupId == id);
        }
    }
}

Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using gestionabscence.Models;
using Microsoft.AspNetCore.Identity;
using GestionAbscences.Helpers;

namespace GestionAbscences.Controllers
{
    public class UsersController : Controller
    {
        private readonly MyDbContext _context;


        public UsersController(MyDbContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
           
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            return View(await _context.Users.ToListAsync());
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,IdCard,Email,Password,BirthDate,Address,Phone,Gender,Role")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Password = PasswordHelper.HashPassword(user.Password);
                _context.Add(user);
                await _context.SaveChangesAsync();
                if (user.Role == "Student")
                {
                    var usrId = user.Id;
                    Student student = new Student();
                    student.UserId = usrId;
                    _context.Add(student);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    var usrId = user.Id;
                    Professor prof = new Professor();
                    prof.UserId = usrId;
                    _context.Add(prof);
                    await _context.SaveChangesAsync();
                }
                
                return RedirectToAction(nameof(Index));
                

            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            try
            {
                _context.Update(user);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(user.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestionAbscences</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
    <link rel="stylesheet" href="~/sidebare/css/style.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="~/GestionAbscences.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="wrapper d-flex align-items-stretch">
        @if (User.Identity.IsAuthenticated)
        {
            <nav id="sidebar" class="active">
                <h1><a href="index.html" class="logo">M.</a></h1>
            <ul class="list-unstyled components mb-5">
                <li class="active">
                    <a href="#"><span class="fa fa-home"></span> Home</a>
                </li>
                    @if (User.IsInRole("Admin"))
                    {
                    <li>
                            <a asp-area="" asp-controller="Users" asp-action="Index"><span class="fa fa-user"></span> Users</a>
                    </li>
                    }
                <li>
                        <a asp-area="" asp-controller="Groups" asp-action="Index"><span class="fa fa-sticky-note"></span> Groups</a>
                </li>
                <li>
                        <a asp-area="" asp-controller="Students" asp-action="Index"><span class="fa fa-users"></span> Students</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Professors" asp-action="Index"><span class="fa fa-user-circle-o"></span> Professors</a>
                </li>
                <li>
                        <a asp-area="" asp-controller="Subjects" asp-action="Index"><span class="fa fa-book"></span> Subjects</a>
                </li>
                    <li>
                        <a asp-area="" asp-controller="Absences" asp-action="Index"><span class="fa fa-user-times"></span> Absences</a>
                    </li>
                <li>
                    <a href="#"><span class="fa fa-paper-plane"></span> Contacts</a>
                </li>
            </ul>

         
        </nav>
        }

        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-5">
             @if (User.Identity.IsAuthenticated)
            {
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-primary">
                        <i class="fa fa-bars"></i>
                        <span class="sr-only">Toggle Menu</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fa fa-bars"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                             <form asp-controller="Account" asp-action="Logout" method="post" class="form-inline">
                                <li class="nav-item active">
                                    <button type="submit" class="btn btn-link nav-link" style="cursor: pointer;">Logout</button>
                                </li>
                             </form>
                            

                        </ul>
                    </div>
                </div>
            </nav>
            }
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>

           @*  <div class="footer">
                <p>
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib.com</a>
                </p>
            </div> *@
            
        </div>
    </div>
    @* <header>
        @if(User.Identity.IsAuthenticated)
        {
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GestionAbscences</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                            @if (User.IsInRole("Admin"))
                            {
                                 <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                                </li>
                            }
                           
                    </ul>
                </div>
            </div>
        </nav>
        }
    </header> *@
   @*  <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div> *@

   @*  <footer class="border-top footer text-muted p-6">
        <div class="container">
            &copy; 2024 - GestionAbscences - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/sidebare/js/popper.js"></script>
    <script src="~/sidebare/js/main.js"></script>
    @* <script src="~/js/site.js" asp-append-version="true"></script> *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>